[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = ""
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
REPO_URL = "https://github.com/your-username/your-repo"
RUNNER_TOKEN = "your-github-runner-token"
RUNNER_NAME = "railway-runner"
RUNNER_LABELS = "railway"

[requiredVariables]
REPO_URL = "The URL of your GitHub repository (e.g., https://github.com/username/repo)"
RUNNER_TOKEN = "GitHub Actions runner registration token from your repository settings"

[optionalVariables]
RUNNER_NAME = "Custom name for your runner (default: railway-runner)"
RUNNER_LABELS = "Comma-separated list of labels (default: railway)" 